import { chromium } from './node_modules/playwright-core/index.mjs'
import assert from 'node:assert/strict'
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('pageerror', e => errors.push(e.message))
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' })
await page.waitForTimeout(1600)
const hint = page.locator('[data-scroll-hint]')
assert.equal(await hint.count(), 1)
const height = await page.evaluate(() => document.documentElement.scrollHeight)
await hint.click()
await page.waitForTimeout(1400)
const y = await page.evaluate(() => scrollY)
assert.ok(y > 300 && y <= 361)
assert.equal(await page.evaluate(() => document.documentElement.scrollHeight), height)
for (const offset of [1400, 2450, 3550, 6500, 9000, 14000, 19000]) {
  await page.evaluate(y => scrollTo(0,y), offset)
  await page.waitForTimeout(900)
  assert.equal(await hint.isVisible(), true, `hint visible at ${offset}`)
}
await page.screenshot({ path: '.tmp/browser-check/hint-dark.png' })
await page.evaluate(() => scrollTo(0, document.documentElement.scrollHeight))
await page.waitForTimeout(1400)
assert.equal(await hint.count(), 0, 'hide at bottom')
await page.evaluate(() => scrollTo(0, 2450))
await page.waitForTimeout(1100)
assert.equal(await hint.isVisible(), true, 'return when scrolling up')
await page.screenshot({ path: '.tmp/browser-check/hint-light.png' })
await page.goto('http://127.0.0.1:5173/products', { waitUntil: 'networkidle' })
await page.waitForTimeout(1300)
assert.equal(await hint.count(), 0, 'no hint on non-scrollable product grid')
const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
await mobile.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' })
await mobile.waitForTimeout(1500)
assert.equal(await mobile.getByText('上滑继续', { exact: true }).isVisible(), true)
await mobile.screenshot({ path: '.tmp/browser-check/hint-mobile.png' })
assert.deepEqual(errors, [])
console.log('PASS: visible across home sections, click scrolls 360px without changing page height, hides at bottom and on non-scrollable route, touch wording, no errors')
await browser.close()
